# Generated by Django 5.0 on 2023-12-06 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orquestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sinfonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('compositor', models.CharField(max_length=100)),
                ('data_criacao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AptoA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcao')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.musico')),
            ],
        ),
        migrations.CreateModel(
            name='Compoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.musico')),
                ('orquestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orquestra')),
            ],
        ),
        migrations.CreateModel(
            name='Executa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desempenho', models.CharField(blank=True, max_length=100, null=True)),
                ('orquestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orquestra')),
                ('sinfonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sinfonia')),
            ],
        ),
        migrations.CreateModel(
            name='Apresenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcao')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.musico')),
                ('sinfonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sinfonia')),
            ],
        ),
        migrations.CreateModel(
            name='Usa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcao')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrumento')),
            ],
        ),
    ]
